# Generated by Django 5.2.3 on 2025-07-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='img',
            new_name='profileimg',
        ),
    ]
